---

- name: Pre hooks
  include: '{{ lookup("task_src", "freeipa_client/pre_main.yml") }}'

- name: Make sure that Ansible local facts directory exists
  file:
    path: '/etc/ansible/facts.d'
    state: 'directory'
    owner: 'root'
    group: 'root'
    mode: '0755'

- name: Save local facts
  template:
    src: '{{ lookup("template_src", "etc/ansible/facts.d/freeipa_client.fact.j2") }}'
    dest: '/etc/ansible/facts.d/freeipa_client.fact'
    owner: 'root'
    group: 'root'
    mode: '0644'
  register: freeipa_client_register_facts
  notify: [ 'Gather FreeIPA client facts' ]

- name: Create IPA configuration directory
  file:
    path: '/etc/ipa'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: Download IPA CA certificate
  get_url:
    url: 'https://{{ freeipa_servers[0] }}/ipa/config/ca.crt'
    validate_certs: 'no'
    dest: '/etc/ipa/ca.crt'

- name: Configure IPA client
  template:
    src: '{{ lookup("template_src", "etc/ipa/default.conf.j2") }}'
    dest: '/etc/ipa/default.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'

- include: sssd.yml

- include: certificates.yml
  when: freeipa_client_pki is defined and freeipa_client_pki

- include: ssh_client.yml

- include: pam.yml

- name: Post hooks
  include: '{{ lookup("task_src", "freeipa_client/post_main.yml") }}'
