---

- name: Install SSSD packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: 'no'
  with_items:
    - 'sssd'
    - 'sssd-tools'
    - 'libpam-sss'
    - 'libnss-sss'
    - 'libsasl2-modules-ldap'
    - 'libsasl2-modules-gssapi-mit'
    - 'sudo'
    - 'cracklib-runtime'
    - '{{ "libsss-sudo" if (( ansible_lsb.id == "Debian" and ansible_lsb.major_release | version_compare("8", ">=")) or
                           ( ansible_lsb.id == "Ubuntu" and ansible_lsb.major_release | version_compare("14.04", ">=" ))) else "libsss-sudo0" }}' 

- name: Configure SSSD for IPA server
  template:
    src: '{{ lookup("template_src", "etc/sssd/sssd.conf.j2") }}'
    dest: '/etc/sssd/sssd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: [ Restart sssd ]

- name: Set nsswitch.conf lookup methods
  set_fact:
    auth_nsswitch: "{{ auth_nsswitch }}"

- include: krb5.yml
