---

- name: Install SSSD packages
  apt:
    name: '{{ item }}'
    state: 'latest'
    install_recommends: 'no'
  with_items: [ 'krb5-user', 'sssd', 'sssd-tools', 'libsasl2-modules-ldap', 'libsasl2-modules-gssapi-mit', 'libpam-sss', 'libnss-sss', 'sudo', 'libsss-sudo',  ]

- name: Divert original /etc/krb5.conf
  command: dpkg-divert --quiet --local --divert /etc/krb5.conf.dpkg-divert --rename /etc/krb5.conf
           creates=/etc/krb5.conf.dpkg-divert

- name: Create IPA configuration directory
  file:
    path: '/etc/ipa'
    owner: 'root'
    group: 'root'
    mode: '0755'
    state: 'directory'

- name: Download IPA CA certificate
  get_url:
    url: 'https://{{ freeipa_servers[0] }}/ipa/config/ca.crt'
    validate_certs: 'no'
    dest: '/etc/ipa/ca.crt'

- name: Configure SSSD for IPA server
  template:
    src: 'etc/sssd/sssd.conf.j2'
    dest: '/etc/sssd/sssd.conf'
    owner: 'root'
    group: 'root'
    mode: '0600'
  notify: [ Restart sssd ]

- name: Configure kerberos client
  template:
    src: 'etc/krb5.conf.j2'
    dest: '/etc/krb5.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: [ Restart sssd ] 

- name: Set nsswitch.conf lookup methods
  set_fact:
    auth_nsswitch: "{{ auth_nsswitch }}"
